# Copyright Cetmix OÜ 2024
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).
{
    "name": "Cetmix Tower YAML",
    "summary": "Cetmix Tower YAML export/import",
    "version": "18.0.1.0.2",
    "development_status": "Beta",
    "category": "Productivity",
    "website": "https://tower.cetmix.com",
    "author": "Cetmix",
    "license": "AGPL-3",
    "installable": True,
    "depends": ["cetmix_tower_server"],
    "external_dependencies": {"python": ["pyyaml"]},
    "data": [
        "security/cetmix_tower_yaml_groups.xml",
        "security/cx_tower_yaml_wizard_access_rules.xml",
        "security/ir.model.access.csv",
        "views/cx_tower_command_view.xml",
        "views/cx_tower_file_template_view.xml",
        "views/cx_tower_plan_view.xml",
        "views/cx_tower_server_template_view.xml",
        "views/cx_tower_server_view.xml",
        "views/cx_tower_variable_view.xml",
        "views/cx_tower_variable_value_view.xml",
        "views/cx_tower_os_view.xml",
        "views/cx_tower_tag_view.xml",
        "views/cx_tower_shortcut_view.xml",
        "views/cx_tower_scheduled_task_view.xml",
        "views/cx_tower_key_view.xml",
        "views/cx_tower_yaml_manifest_template_views.xml",
        "views/cx_tower_yaml_manifest_author_views.xml",
        "wizards/cx_tower_yaml_export_wiz.xml",
        "wizards/cx_tower_yaml_export_wiz_download.xml",
        "wizards/cx_tower_yaml_import_wiz_upload.xml",
        "wizards/cx_tower_yaml_import_wiz.xml",
        "views/menuitems.xml",
    ],
    "demo": [
        "demo/demo_data.xml",
    ],
}
