version: "2"

services:
  web:
    build:
      context: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      HOST: 172.17.0.1
      PASSWORD: odoo
      PORT: 32769
      USER: odoo
    restart: unless-stopped
    ports:
      - 127.0.0.1:8089:8069
    command:
      - -d
      - 14_cetmix_tower
      - -u
      - cx_tower_server
    volumes:
      - /home/i1/odoo/14/extra-addons/cetmix-tower:/mnt/extra-addons
