[project]
name = "odoo-addons-cetmix-cetmix-tower"
version = "18.0.20251203.0"
dependencies = [
    "odoo-addon-cetmix_tower_server==18.0.*",
    "odoo-addon-cetmix_tower_yaml==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
