# Copyright Cetmix OÜ 2022
#  License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).
{
    "name": "Cetmix Tower Server",
    "summary": "Manage servers and applications from Odoo",
    "version": "18.0.1.0.5",
    "category": "Productivity",
    "website": "https://tower.cetmix.com",
    "live_test_url": "https://tower.cetmix.com/download",
    "images": ["static/description/banner.png"],
    "author": "Cetmix",
    "license": "AGPL-3",
    "application": False,
    "installable": True,
    "external_dependencies": {
        "python": ["paramiko<4", "tldextract", "dnspython", "ansi2html"],
    },
    "depends": [
        "mail",
        "rpc_helper",
        "web_notify",
    ],
    "data": [
        "security/cetmix_tower_server_groups.xml",
        "security/ir.model.access.csv",
        "security/cx_tower_server_security.xml",
        "security/cx_tower_command_security.xml",
        "security/cx_tower_plan_security.xml",
        "security/cx_tower_plan_line_security.xml",
        "security/cx_tower_plan_line_action_security.xml",
        "security/cx_tower_plan_log_security.xml",
        "security/cx_tower_server_log_security.xml",
        "security/cx_tower_command_log_security.xml",
        "security/cx_tower_server_template_security.xml",
        "security/cx_tower_file_security.xml",
        "security/cx_tower_file_template_security.xml",
        "security/cx_tower_variable_security.xml",
        "security/cx_tower_variable_value_security.xml",
        "security/cx_tower_variable_option_security.xml",
        "security/cx_tower_scheduled_task_security.xml",
        "security/cx_tower_scheduled_task_cv_security.xml",
        "security/cx_tower_key_security.xml",
        "security/cx_tower_key_value_security.xml",
        "security/cx_tower_tag_security.xml",
        "security/cx_tower_shortcut_security.xml",
        "security/cx_tower_server_wizard_access_rules.xml",
        "data/ir_cron.xml",
        "data/ir_config_parameter.xml",
        "wizards/cx_tower_command_run_wizard_view.xml",
        "wizards/cx_tower_plan_run_wizard_view.xml",
        "wizards/cx_tower_server_template_create_wizard_view.xml",
        "wizards/cx_tower_server_host_key_wizard_view.xml",
        "views/cx_tower_server_view.xml",
        "views/cx_tower_os_view.xml",
        "views/cx_tower_tag_view.xml",
        "views/cx_tower_variable_view.xml",
        "views/cx_tower_variable_value_view.xml",
        "views/cx_tower_command_view.xml",
        "views/cx_tower_plan_view.xml",
        "views/cx_tower_plan_line_view.xml",
        "views/cx_tower_plan_line_view_action_view.xml",
        "views/cx_tower_command_log_view.xml",
        "views/cx_tower_plan_log_view.xml",
        "views/cx_tower_key_view.xml",
        "views/cx_tower_file_view.xml",
        "views/cx_tower_file_template_view.xml",
        "views/cx_tower_server_log_view.xml",
        "views/cx_tower_server_template_view.xml",
        "views/cx_tower_shortcut_view.xml",
        "views/cx_tower_scheduled_task_view.xml",
        "views/res_partner_view.xml",
        "views/res_config_settings.xml",
        "views/menuitems.xml",
    ],
    "demo": [
        "demo/demo_data.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "cetmix_tower_server/static/src/components/**/*.xml",
            "cetmix_tower_server/static/src/**/*.js",
            "cetmix_tower_server/static/src/**/*.scss",
        ],
    },
}
